import { Theme } from "@/lib/themes";

export function defineMonacoThemes(monaco: any, themes: Theme[]) {
  themes.forEach(theme => {
    // Define light theme
    monaco.editor.defineTheme(`${theme.name}-light`, {
      base: "vs",
      inherit: true,
      rules: [
        { token: "comment", foreground: "6A9955", fontStyle: "italic" },
        { token: "keyword", foreground: "0000FF" },
        { token: "string", foreground: "A31515" },
        { token: "number", foreground: "098658" },
        { token: "regexp", foreground: "811F3F" },
        { token: "operator", foreground: "000000" },
        { token: "namespace", foreground: "267F99" },
        { token: "type", foreground: "267F99" },
        { token: "struct", foreground: "267F99" },
        { token: "class", foreground: "267F99" },
        { token: "interface", foreground: "267F99" },
        { token: "parameter", foreground: "001080" },
        { token: "variable", foreground: "001080" },
        { token: "function", foreground: "795E26" },
        { token: "method", foreground: "795E26" },
        { token: "property", foreground: "001080" },
        { token: "tag", foreground: "800000" },
        { token: "attribute.name", foreground: "FF0000" },
        { token: "attribute.value", foreground: "0451A5" },
      ],
      colors: {
        "editor.background": theme.cssVars.light["--background"] || "#ffffff",
        "editor.foreground": theme.cssVars.light["--foreground"] || "#000000",
        "editorLineNumber.foreground": theme.cssVars.light["--muted-foreground"] || "#237893",
        "editorLineNumber.activeForeground": theme.cssVars.light["--foreground"] || "#000000",
        "editor.selectionBackground": theme.cssVars.light["--accent"] || "#ADD6FF26",
        "editor.selectionHighlightBackground": theme.cssVars.light["--accent"] || "#ADD6FF26",
        "editorCursor.foreground": theme.cssVars.light["--primary"] || "#0000FF",
        "editorWhitespace.foreground": theme.cssVars.light["--muted-foreground"] || "#D3D3D3",
        "editorIndentGuide.background": theme.cssVars.light["--border"] || "#D3D3D3",
        "editorIndentGuide.activeBackground": theme.cssVars.light["--foreground"] || "#000000",
        "editorBracketMatch.background": theme.cssVars.light["--accent"] || "#ADD6FF26",
        "editorBracketMatch.border": theme.cssVars.light["--border"] || "#D3D3D3",
        "editorGutter.background": theme.cssVars.light["--background"] || "#ffffff",
        "editorLineHighlight.background": theme.cssVars.light["--muted"] || "#F5F5F5",
        "editorWidget.background": theme.cssVars.light["--popover"] || "#ffffff",
        "editorWidget.border": theme.cssVars.light["--border"] || "#D3D3D3",
        "editorSuggestWidget.background": theme.cssVars.light["--popover"] || "#ffffff",
        "editorSuggestWidget.border": theme.cssVars.light["--border"] || "#D3D3D3",
        "editorSuggestWidget.foreground": theme.cssVars.light["--popover-foreground"] || "#000000",
        "editorSuggestWidget.highlightForeground": theme.cssVars.light["--primary"] || "#0000FF",
        "editorSuggestWidget.selectedBackground": theme.cssVars.light["--accent"] || "#ADD6FF26",
        "editorHoverWidget.background": theme.cssVars.light["--popover"] || "#ffffff",
        "editorHoverWidget.border": theme.cssVars.light["--border"] || "#D3D3D3",
        "editorHoverWidget.foreground": theme.cssVars.light["--popover-foreground"] || "#000000",
        "editorError.foreground": theme.cssVars.light["--destructive"] || "#E51400",
        "editorWarning.foreground": "#FF8C00",
        "editorInfo.foreground": theme.cssVars.light["--primary"] || "#0000FF",
      },
    });

    // Define dark theme
    monaco.editor.defineTheme(`${theme.name}-dark`, {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "comment", foreground: "6A9955", fontStyle: "italic" },
        { token: "keyword", foreground: "569CD6" },
        { token: "string", foreground: "CE9178" },
        { token: "number", foreground: "B5CEA8" },
        { token: "regexp", foreground: "D16969" },
        { token: "operator", foreground: "D4D4D4" },
        { token: "namespace", foreground: "4EC9B0" },
        { token: "type", foreground: "4EC9B0" },
        { token: "struct", foreground: "4EC9B0" },
        { token: "class", foreground: "4EC9B0" },
        { token: "interface", foreground: "4EC9B0" },
        { token: "parameter", foreground: "9CDCFE" },
        { token: "variable", foreground: "9CDCFE" },
        { token: "function", foreground: "DCDCAA" },
        { token: "method", foreground: "DCDCAA" },
        { token: "property", foreground: "9CDCFE" },
        { token: "tag", foreground: "569CD6" },
        { token: "attribute.name", foreground: "92C5F8" },
        { token: "attribute.value", foreground: "CE9178" },
      ],
      colors: {
        "editor.background": theme.cssVars.dark["--background"] || "#1e1e1e",
        "editor.foreground": theme.cssVars.dark["--foreground"] || "#d4d4d4",
        "editorLineNumber.foreground": theme.cssVars.dark["--muted-foreground"] || "#858585",
        "editorLineNumber.activeForeground": theme.cssVars.dark["--foreground"] || "#d4d4d4",
        "editor.selectionBackground": theme.cssVars.dark["--accent"] || "#264F78",
        "editor.selectionHighlightBackground": theme.cssVars.dark["--accent"] || "#264F78",
        "editorCursor.foreground": theme.cssVars.dark["--primary"] || "#AEAFAD",
        "editorWhitespace.foreground": theme.cssVars.dark["--muted-foreground"] || "#3C3C3C",
        "editorIndentGuide.background": theme.cssVars.dark["--border"] || "#3C3C3C",
        "editorIndentGuide.activeBackground": theme.cssVars.dark["--foreground"] || "#d4d4d4",
        "editorBracketMatch.background": theme.cssVars.dark["--accent"] || "#264F78",
        "editorBracketMatch.border": theme.cssVars.dark["--border"] || "#3C3C3C",
        "editorGutter.background": theme.cssVars.dark["--background"] || "#1e1e1e",
        "editorLineHighlight.background": theme.cssVars.dark["--muted"] || "#2A2D2E",
        "editorWidget.background": theme.cssVars.dark["--popover"] || "#252526",
        "editorWidget.border": theme.cssVars.dark["--border"] || "#3C3C3C",
        "editorSuggestWidget.background": theme.cssVars.dark["--popover"] || "#252526",
        "editorSuggestWidget.border": theme.cssVars.dark["--border"] || "#3C3C3C",
        "editorSuggestWidget.foreground": theme.cssVars.dark["--popover-foreground"] || "#CCCCCC",
        "editorSuggestWidget.highlightForeground": theme.cssVars.dark["--primary"] || "#007ACC",
        "editorSuggestWidget.selectedBackground": theme.cssVars.dark["--accent"] || "#264F78",
        "editorHoverWidget.background": theme.cssVars.dark["--popover"] || "#252526",
        "editorHoverWidget.border": theme.cssVars.dark["--border"] || "#3C3C3C",
        "editorHoverWidget.foreground": theme.cssVars.dark["--popover-foreground"] || "#CCCCCC",
        "editorError.foreground": theme.cssVars.dark["--destructive"] || "#F44747",
        "editorWarning.foreground": "#FFCC02",
        "editorInfo.foreground": theme.cssVars.dark["--primary"] || "#007ACC",
      },
    });
  });
}
